@startuml backend
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

title Component diagram for Backend API


System_Boundary(api, "Backend API") {
    ' Engagement context
    Component(contests, "Contests", "module", "Manages challenges, capture-the-flags and hackathons")  
    Component(meetings, "Meetings", "module", "Manages calls between mentors and candidaters, community leaders and NPOs")
    Component(messengers, "Messengers", "module", "Integrates social messengers")
    Component(messengers, "Messengers", "module", "Integrates social messengers")
    Component(notifications, "Notifications", "module", "Manages Push notifications/Emails")
    Component(bragging, "Bragging", "module", "Manages candidates and NPOs badges and awards")
  
    ' NPO context  
    Component(npo_assessments, "NPO Assessments", "module", "Manages NPO assessments")
    Component(volunteer_assessments, "Volunteer Assessments", "module", "Manages Volunteer assessments")
    Component(npo_recommendations, "NPO Recommendations", "module", "Matches candidate assessment against NPOs and their services")    
    Component(npo_services, "NPO Services", "module", "Manages list of the services for NPO and communicates changes with Taxonomy")      
    Component(mentor_search, "Mentor Search", "module", "Brings search functionality for mentors")      
    Component(partnerships, "Partnerships", "module", "Manages partnership flow for NPOs")
  
    ' Communities context
    Component(communities, "Communities", "module", "Manages communities and related permissions")  
    Component(leaders, "Community Leaders", "module", "Manages assignments for communities")
    Component(events, "Events", "module", "Manages events (weekly spotlives, masterminds, AMA sessions)")  
    Component(ratings, "Ratings", "module", "Manages ratings for UGC content")
    Component(taxonomy, "Service Taxonomy", "module", "Serves service offering catalog, enables search engine")
    Component(profanity_checks, "Profanity checks", "module", "Provides profanity filters for UGC")  
  
    ' Reporting Context
    Component(reporting, "Reporting", "module", "Provides operational reports")
    Component(analytics, "Analytics", "module", "Provides analytics and trends")
    Component(tracking, "Tracking", "module", "Tracks progress over candidates and NPOs")
    
    ' Document Exchange Context    
    Component(docrender, "Document Rendering", "module", "Renders PDF")
    Component(docparser, "Document Parsing", "module", "Parses different types of documents")
    Component(dockeeper, "Secure Document Storage", "module", "Store documents in safe manner")
      
    ' Candidates Context
    Component(candidates, "Candidates", "module", "Manages candidates")
    Component(roadmaps, "Career Roadmaps", "module", "Manages career roadmaps for candidates with quality gates")
    Component(candidate_assessments, "Candidate Assessments", "module", "Manages candidates assessments")
}

@enduml
