@startuml Spotlight context diagram
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml

title Context diagram for Spotlight platform

LAYOUT_WITH_LEGEND()

Person(community_leader, "Community Leader", "A platform administrator for DCC Spotlight")
Person(npo_admin, "NPO Admin", "a NPO leader")
Person(mentor, "Mentor", "a Mentor")
Person(candidate, "Candidate", "a person with certain need")
Person_Ext(visitor, "Visitor", "a person with interest")

System_Boundary(spotlight, "Spotlight platform") {
    System(spa_app, "Single Page Application (ReactJs)", "Provides WEB interface")
    System(mobile_app, "Mobile Application (iOs/Android/Aurora)", "Provides portable (smartphone/tablet) access")    
    System(api, "Backend API", "Drives the business logic and enforces constraints")
}

System_Ext(s3, "File storage", "Handles storage of files")
System_Ext(ses, "Notification service", "Handles push notifications and transactional emails")
System_Ext(rds, "Database", "Handles data persistance")
System_Ext(serverless, "Computing power", "Renders PDFs in scalable way")

Rel(community_leader, spa_app, "Supports and Reviews NPOs")
Rel(npo_admin, spa_app, "Register NPO, publish content, manages mentors")

Rel(mentor, mobile_app, "Supports Candidates, setup Career Roadmap for candidate")
Rel(candidate, mobile_app, "Applies for and consumes services")
Rel(visitor, mobile_app, "Looks for content")

Rel(spa_app, api, "request")
Rel(mobile_app, api, "request")

Rel(api, s3, "(Optionally) stores files in ")
Rel(api, ses, "(Optionally) sends notifications via ")
Rel(api, rds, "(Optionally) stores data via ")
Rel(api, serverless, "(Optionally) uses computing power via ")

@enduml
